---
- name: Add/update setting file
  ansible.builtin.template:
    src: openvpn.j2
    dest: /erc/openvpn/openvpn.conf
    mode: "0644"
- name: Add/update custom setting line
  ansible.builtin.lineinfile:
    path: /etc/openvpn/openvpn.conf
    regexp: ^(#\s+)?option_name=
    line: option_name=option_value
- name: Add/update custom setting block
  ansible.builtin.blockinfile:
    path: /etc/openvpn/openvpn.conf
    block: "{{ role_extra_cfg }}"
